### ISSUE TITLE
cuda gpu不可用

### ISSUE THREAD

**Issue by Fino2020** [HLT-HITSZ/MGF#4]
![image](https://user-images.githubusercontent.com/66312471/190109779-3af9a0ab-24e1-45c0-8dbd-e992f8ce6491.png)
由于显卡缘故，我在cuda11。1下运行，torch版本为1.8.0+cu111，dgl版本为dgl-cu111==0.6.1，并且在python控制台可以检测到gpu
![image](https://user-images.githubusercontent.com/66312471/190110046-d0f4bc34-acf2-4fd5-8081-cd5512e847e2.png)
请问这是什么原因捏？

**Comment by Fino2020** [comment]
![image](https://user-images.githubusercontent.com/66312471/190110483-891d2cf3-f86d-4599-b3ce-64b671a8ecd8.png)
同时models.py中dgl.nn库中的GraphConv，EdgeWeightNorm两个函数也不存在

**Comment by Fino2020** [comment]
解决了，在调包的时候测试一下cuda是否可用，后面就可以用了，好神奇的bug，貌似应该是torch版本的问题
![image](https://user-images.githubusercontent.com/66312471/190151634-f7f00ade-d086-43cf-a631-dd5b93b11f25.png)

**Comment by Fino2020** [comment]
但是出现了一个新问题，运行run.py后出现这样的结果，没有出现训练和测试就结束了，请问这个结果在哪呀，或者我出了什么问题？
![image](https://user-images.githubusercontent.com/66312471/190164206-263fa80a-7f74-4344-b3e5-8ac091ccfdce.png)

**Comment by HLT-HITSZ** [comment]
您好！可以在saved_models中查看训练log
